# pyproject.toml

[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "UniDec"
version = "9.0.0"
description = "Universal Deconvolution of Mass and Ion Mobility Spectra"
readme = "readme.md"
authors = [{ name = "Michael Marty", email = "mtmarty@utexas.edu" }]
license = { file = "LICENSE" }
classifiers = [
    #"License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["Mass Spectrometry", "Ion Mobility", "Deconvolution"]
dependencies = ["numpy>=2.0.0", "scipy>=1.2", "matplotlib>=3.7", 'pandas',
                      "pymzml", "natsort", "networkx", "h5py", "pypubsub", "numba",
                      "pyimzml", "isodec>=2.0.1", "pyisogen>=1.0.8", "pythonnet; platform_system == 'Windows'", "pyteomics",
                      "UniDecImporter>=0.1.0", "lxml", "lxml_html_clean", "pywin32; platform_system == 'Windows'"]
requires-python = ">=3.10"

[project.optional-dependencies]
# install with <installer> install '.[opt-dependency group]'
dev = ["pytest", "pyinstaller", "molmass", "mpld3",
    "wxpython>=4.0"]
img = ['pyimzml']

[project.urls]
Homepage = "https://github.com/michaelmarty/UniDec"
Documentation = "https://michaelmarty.github.io/UniDec/"
Repository = "https://github.com/michaelmarty/UniDec"
Issues = "https://github.com/michaelmarty/UniDec/issues"

[project.scripts]
unidec = "unidec.__main__:main"
gunidec = "unidec.Launcher:run_launcher"
isodec = "isodec.__main__:main"

[tool.setuptools]
include-package-data = true

#[tool.setuptools.packages.find]
#where = ["unidec"]
#
#[tool.setuptools.package_data]

[tool.setuptools.package-dir]
# define the subdirectory (from the parent directory containing this pyproject
# file) to define as the root directory of the package.
unidec = "unidec"

[project.gui-scripts]
# define a command to open the unidec GUI
gunidec = "unidec.Launcher:run_launcher"

[tool.uv.sources]
unidec = { workspace = true }

[tool.uv.workspace]
members = [
    ".",
    ".",
]
